config/routes.rb
Rails.application.routes.draw do
  
  root 'bills#index'

  resources :bills
  resources :paid_bills

end

app/models/bill.rb
class Bill < ActiveRecord::Base

	before_update :update_paid_at

	def update_paid_at
		if self.paid && !self.paid_at
			self.paid_at = Date.new
		end
	end

end

app/models/paid_bill.rb
paid_bill.rb

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

 def index
 	@bills = Bill.where(paid: false)
 end

 def new
 	@bill = Bill.new
 end

 def create
 	@bill = Bill.create(bill_params)
 	redirect_to :root
 end

 def show
 	@bill = Bill.find(params[:id])
 end

 def edit
 	@bill = Bill.find(params[:id])
 end

 def update
 	@bill = Bill.find(params[:id])
 	@bill.update(bill_params)
 	redirect_to :root
 end

 def destroy
 	@bill = Bill.find(params[:id])
 	@bill.delete
 	redirect_to :root
 end

private
def bill_params
	params
	.require(:bill)
	.permit(:min_pay, :bill_name, :link, :paid, :payment_date, :paid_at)
 end
end

app/controllers/paid_bills_controller.rb
class PaidBillsController < ApplicationController

def index
	@bills = Bill.where(paid: true)
end
private
def bill_params
	params
	.require(:bill)
	.permit(:min_pay, :bill_name, :link, :payment_date, :paid_at)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bills/edit.html.erb
<%= form_for(@bill) do |f| %>
    <%= f.label :bill_name %>
    <%= f.text_field :bill_name %>
    <%= f.label :payment_date %>
    <%= f.text_field :payment_date %>
    <%= f.label :min_pay %>
    <%= f.text_field :min_pay %>
    <%= f.label :link %>
    <%= f.text_field :link %>
    <%= f.submit %>
    <% end %>

app/views/bills/index.html.erb
	<div class="row">
	<% @bills.each do |bills| %>

	<div class="bill columns large-4 medium-6 small-12">
	<%= link_to bills.bill_name, bill_path(bills) %><br>
	Pay Date:   <%= bills.payment_date %><br>
	 Minimum Payment:   $<%= bills.min_pay %><br>
	 <a href='<%= bills.link %>'> Pay Bill</a>
	</div>
	<% end %>
	</div>

	<div class="closing row small-12 large-12 medium-12">
		<a href="http://localhost:3000/paid_bills" class="button round">Paid History</a>
	</div>

app/views/bills/new.html.erb
<%= form_for(@bill) do |f| %>
    <%= f.label :bill_name %>
    <%= f.text_field :bill_name %>
    <%= f.label :payment_date %>
    <%= f.text_field :payment_date %>
    <%= f.label :min_pay %>
    <%= f.text_field :min_pay %>
    <%= f.label :link %>
    <%= f.text_field :link %>
    <%= f.submit %>
    <% end %>

app/views/bills/show.html.erb
	<div class="show bill columns large-4 medium-6 small-12">
	<h1><%= @bill.bill_name %></h1><br>
	Minimum Payment:  $<%= @bill.min_pay %><br>
	<a href='<%= @bill.link %>'> Pay Bill Now</a><br>
	Payment Due Date: <%= @bill.payment_date %><br>
	<%= form_for(@bill) do |f| %>
	<%= hidden_field(:bill, :paid, :value => true) %>
	<%= f.submit "Pay Bill", class: 'button'%>
    <% end %>
	<a><%= link_to 'edit', edit_bill_path(@bill) %></a>                 
	<%= link_to 'delete', bill_path(@bill), { 
	method: :delete} %>	
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<div class="row page-header">
  <div class="columns text-center">
    <img class="header" src="http://i.imgur.com/dfD5e8l.png">
  </div>
  <a href="http://localhost:3000/bills/new.%23%3CBill::ActiveRecord_Relation:0x007fab6a7e5c08%3E" class="button radius" target="_blank">Add A Bill</a>
</div>
    <%= yield %>

  </body>
</html>

app/views/paid_bills/index.html.erb
	<div class="row">
	<% @bills.each do |bills| %>

	<div class="bill columns large-4 medium-6 small-12">
	<h3><%= bills.bill_name %> </h3>
	Minimum Payment: $<%= bills.min_pay %><br>
	Time Paid: <%= bills.updated_at %>

	</div>
	<% end %>
	</div>

	<div class="closing row small-12 large-12 medium-12">
	<a href="http://localhost:3000/" class="button round">Unpaid Bills</a>
	</div>